### ISSUE TITLE
What is the correlation between pbsmrtpip and smrtanalysis protocols? 

### ISSUE THREAD

**Issue by yech1990** [PacificBiosciences/pbsmrtpipe#498]
I notice that `pbsmrtpipe` protocols are named as \*\_sa3_ds\_\*, where 'sa3' and 'ds' look like abbreviations.
> I have two questions.

1. Whether 'sa3' is short for `Smrt Analysis 3.0` ?
2. The protocols in `smrtanalysis-2.3.0` don't have 'sa3' in there file names. Does it means the `smrtanalysis` 2.3.0 version use the old protocols?  

```bash
$ ls ./smrtanalysis/install/smrtanalysis_2.3.0.140936/common/protocols

applications.xml                RS_BridgeMapper.1.xml
assembly                        RS_HGAP_Assembly.2.xml
BAM_Resequencing_Beta.1.xml     RS_HGAP_Assembly.3.xml
barcode                         RS_IsoSeq.1.xml
consensus                       RS_Long_Amplicon_Analysis.1.xml
control                         RS_Minor_Variant.1.xml
filtering                       RS_Modification_and_Motif_Analysis.1.xml
isoseq                          RS_Modification_Detection.1.xml
mapping                         RS_PreAssembler.2.xml
New_Protocol_Assembly.template  RS_ReadsOfInsert.1.xml
New_Protocol.template           RS_ReadsOfInsert_Mapping.1.xml
postprocessing                  RS_Resequencing.1.xml
preprocessing                   RS_Resequencing_Barcode.1.xml
referenceuploader               RS_Site_Acceptance_Test.1.xml
RS_AHA_Scaffolding.1.xml        RS_Subreads.1.xml
```

```bash
$ pbsmrtpipe show-templates  | grep sa3

 37. RS movie Align                                                        0.1.0 pbsmrtpipe.pipelines.sa3_align
 38. SubreadSet Mapping                                                    0.1.0 pbsmrtpipe.pipelines.sa3_ds_align
 39. Unrolled Template SubreadSet Mapping                                  0.1.0 pbsmrtpipe.pipelines.sa3_ds_align_unrolled
 40. Barcoding                                                             0.1.0 pbsmrtpipe.pipelines.sa3_ds_barcode
 41. CCS with Barcoding                                                    0.1.0 pbsmrtpipe.pipelines.sa3_ds_barcode_ccs
 42. LAA with Barcoding                                                    0.2.0 pbsmrtpipe.pipelines.sa3_ds_barcode_laa
 43. Circular Consensus Sequences (CCS 2)                                  0.1.0 pbsmrtpipe.pipelines.sa3_ds_ccs
 44. CCS Mapping                                                           0.1.0 pbsmrtpipe.pipelines.sa3_ds_ccs_align
 45. Convert FASTA to ReferenceSet                                         0.1.0 pbsmrtpipe.pipelines.sa3_ds_fasta_to_reference
...
```

**Comment by yech1990** [comment]
If I want to use the latest circular consensus algorithm, CCS2.
Shall I use SMRTanalysis-2.3.0 or pbsmrtpipe ?

**Comment by evolvedmicrobe** [comment]
@yech1990 - If you would like, it is likely easier to run CCS2 directly from the command line, rather than piping it through the framework.  You can compile a version of it here: https://github.com/PacificBiosciences/unanimity

**Comment by yech1990** [comment]
@evolvedmicrobe 
That't awesome. Thanks you very  much?

BTW, I want to know whether the CCS algorithm embedded in smrtanalysis is the latest version?

**Comment by evolvedmicrobe** [comment]
The latest CCS algorithm is not available in smrtanalysis, but only in smrtlink.

**Comment by yech1990** [comment]
@evolvedmicrobe thx
Can you explain what sa3 short for?

**Comment by evolvedmicrobe** [comment]
@mpkocher do you know?

**Comment by yech1990** [comment]
@evolvedmicrobe 
The installation return the following error.

```bash
src/CMakeFiles/ccs.dir/build.make:62: recipe for target 'src/CMakeFiles/ccs.dir/main/ccs.cpp.o' failed
make[2]: *** [src/CMakeFiles/ccs.dir/main/ccs.cpp.o] Error 1
CMakeFiles/Makefile2:164: recipe for target 'src/CMakeFiles/ccs.dir/all' failed
make[1]: *** [src/CMakeFiles/ccs.dir/all] Error 2
Makefile:127: recipe for target 'all' failed
make: *** [all] Error 2
```

There is no issue segment in the unanimity respiratory.

**Comment by mpkocher** [comment]
@yech1990 The majority of the infrastructure in the [new SMRT Link software stack](https://github.com/PacificBiosciences/SMRT-Link) has been redesigned and rewritten. There are several entities that have changed and new core data models have been added, specifically, the idea of a "protocol" and the [new DataSet model](http://pacbiofileformats.readthedocs.io/en/3.0/DataSet.html). 

The protocol concept in SMRT Analysis 2.x has been replaced with Pipeline Template. The XML protocols in SA 2.x often would turn analysis on and off in the graph which yielded unclear outputs and often created difficulties composing computation. 

The SMRT Analysis component within SMRT Link now has Pipeline Templates which can be referenced by id and are fixed units of computation (e.g., pipeline template alpha always returns a Fasta, Gff and CSV file).

The use of "ds" and "sa3" in the pipeline template id suggest that pipeline is DataSet driven and is a SMRT Analysis 3 component within SMRT Link, respectively.  However, it's recommended that details of the pipeline (entry points, task options, pipeline description) should be obtained from pbsmrtpipe instead of relying on values encoded in the pipeline template id.

The `pbsmrtpipe` exe can provide more details about the registered pipeline templates (`pbsmrtpipe show-templates`). Running `pbsmrtpipe show-template-details {pipeline-id}` will show you a summary of the pipeline of interest. Adding `-o defaults.xml` will yield an XML output file with the default task options for that pipeline. Example `pbsmrtpipe show-template-details pbsmrtpipe.pipelines.sa3_ds_ccs_align -o default-options.xml`.

As Nigel has suggested, running the tool directly is usually the recommended model to avoid unnecessary moving pieces. If you need to submit the computation to your local cluster using a scheduler (SGE, PBS), parallelize computation (split up large files into chunks) for scaling purposes, or would like to run any of the pipelines used in the SMRT Link UI from the commandline, you should consider `pbsmrtpipe`.

**Comment by yech1990** [comment]
@mpkocher Does it means that pbsmrtpipe is the superset of the registered pipeline templates?
I wonder why do I need to access CCS2 though unanimity, which is no easy to install.

I have been trying to install `unaimity` for two days, but failed.

**Comment by evolvedmicrobe** [comment]
@yech1990 The error message you listed for the unamity build was unusual because it didn't say what was wrong, was there any other information available?  I submitted a pull here (https://github.com/PacificBiosciences/unanimity/pull/45/files) with two additional instructions which might resolve your issue.

Building from source is not an officially supported route though, and it looks like you have SMRTLink installed, is this correct?
