### ISSUE TITLE
Process killed in slurm

### ISSUE THREAD

**Issue by BlueGirl15** [PacificBiosciences/pbsmrtpipe#608]
The pipeline pbsmrtpipe.pipelines.polished_falcon_fat was killed while using it in slurm, the command I am using is:
pbsmrtpipe pipeline-id pbsmrtpipe.pipelines.polished_falcon_fat -e eid_subread:subread.subreadset.xml --preset-json preset.json

I have two issues here: 
1. The cluster manager is set to sge, how do I set it to slurm?
2. It fails at the step to filter the data, possibly because the cluster manager is set to sge?

**Comment by natechols** [comment]
1. The basic overview is here: https://pbsmrtpipe.readthedocs.io/en/master/configuration_details.html#cluster-manager
2. I would need to see the exact error message to be certain but your guess is probably correct.  You can run with `--local-only` as a control (of course it will be very slow but the filter step should execute quickly at least).

However,
3. If you're using a SMRT Link installation, you might find it easier to use that to configure the cluster settings, since you can just add `--jmstype Slurm` to make the change centrally, and this will provide a preset file that points to the SMRT link wrapper scripts.
4. pbsmrtpipe is deprecated and minimally supported, we have switched to Cromwell in the current SMRT Link release.  I think the new assembly workflows will perform better than the old polished_falcon_fat pipeline.

**Comment by BlueGirl15** [comment]
Thank you @natechols. Using --local-only in the command solved my problem.
