### ISSUE TITLE
How do I increase max-chunks? (Should be thousands.)

### ISSUE THREAD

**Issue by pb-cdunn** [PacificBiosciences/pbsmrtpipe#61]
```python
File "/lustre/hpcprod/cdunn/repo/gh/FALCON-integrate/pbsmrtpipe/pbsmrtpipe/driver.py", line 842, in exe_workflow
workers, shutdown_event, service_uri)
File "/lustre/hpcprod/cdunn/repo/gh/FALCON-integrate/pbsmrtpipe/pbsmrtpipe/driver.py", line 389, in __exe_workflow
B.apply_chunk_operator(bg, global_registry.chunk_operators, global_registry.tasks, max_nchunks)
File "/lustre/hpcprod/cdunn/repo/gh/FALCON-integrate/pbsmrtpipe/pbsmrtpipe/graph/bgraph.py", line 1223, in apply_chunk_operator
raise TaskChunkingError("Task {i} created too many {n} chunks. Max chunks must be <= {m}".format(n=len(pipeline_chunks), m=max_nchunks, i=tnode_))
TaskChunkingError: Task TaskScatterBindingNode pbfalcon.tasks.scatter0_run_daligner_jobs-1 created too many 55 chunks. Max chunks must be <= 24
```

**Comment by mpkocher** [comment]
The current value is set to 64 in constants.py. Do you have your preset.xml set to override that value to 24?

The current model is for chunking tools to be take an CLI option of max nchunks so that this can be configured/tuned at the pipeline level and the chunked tasks adhere to this interface. In other words, if a user sets max nchunks in the preset.xml to be N, scattered/chunked tasks don't create more pipeline chunks than N.

**Comment by pb-cdunn** [comment]
I would like N chunks, which could be large, but I don't care how many servers are used. I'd like pbsmrtpipe to distribute chunks as servers become available.

In some cases, I need 4 processors per distributed job. In other cases, 1 is enough.

How do I accomplish those goals with pbsmrtpipe?

**Comment by pb-cdunn** [comment]
@mdsmith has clarified this for me. Thx!  :sunny:
